project_id = "wxovwxekhsredmsaetkz"

[functions.classify-evidence]
verify_jwt = true

[functions.detect-anomalies]
verify_jwt = true

[functions.predictive-analytics]
verify_jwt = true

[functions.admin-create-user]
verify_jwt = true
